### Creating and displaying values

In [1]:
x = 99

In [2]:
print(x)

99


In [ ]:
x = 1024

: 

In [ ]:
x = 7
x = 99
x = 1024
print(x)
print(y)

: 

In [ ]:
import time

while True:
    print('Hello')
    time.sleep(1)

: 

### Matrices in Python

In [3]:
import numpy as np

In [4]:
A = np.matrix( [[2, -3, 0],  
                [1, 5, 19]] )
print(np.dot(4, A))

[[  8 -12   0]
 [  4  20  76]]


In [5]:
A = np.matrix( [[5, 1, 3]] )
B = np.matrix( [[2],  
                [4],  
                [6]] )
print(np.dot(A, B))

[[32]]


In [6]:
A = np.matrix( [[1, 3, 2],   
                [4, 0, -1]] )
B = np.matrix( [[5, 10],     
                [2, -2],  
                [-3, 6]] )
print(np.dot(A, B)) 

[[ 5 16]
 [23 34]]


In [7]:
print(A * B)

[[ 5 16]
 [23 34]]


In [8]:
A = np.matrix( [[3], 
                [2]] )
B = np.matrix( [[5], 
                [4]] )
print(np.kron(A, B))

[[15]
 [12]
 [10]
 [ 8]]


### Exercise 8

In [9]:
import numpy as np

A = np.matrix( [[1, 2, 3, 0],
                [2, 1, -1, 3]] )
B = np.matrix( [[1, 1, -2],
                [3, 2, -1],
                [0, 4, 3],
                [3, -3, 5]] )
print(np.dot(A, B))
print(A * B)

[[ 7 17  5]
 [14 -9  7]]
[[ 7 17  5]
 [14 -9  7]]


In [10]:
import numpy as np

A = np.matrix( [[2],
                [3],
                [1]] )
B = np.matrix( [[8, 4, 0],
                [1, 3, 5]] )
print(np.kron(A, B))

[[16  8  0]
 [ 2  6 10]
 [24 12  0]
 [ 3  9 15]
 [ 8  4  0]
 [ 1  3  5]]
